[package]
name = "emergence-tauri"
version = "0.6.0"
description = "Emergence"
authors = ["eric@holochain.org"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.70"
resolver = "2"

[lib]
name = "tauri_app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "2.2.0", default-features = false , features = [] }

[dependencies]
tauri = { version = "2.5.1", features = ["devtools"] }
tauri-plugin-holochain = { git = "https://github.com/holochain/android-service-runtime", branch = "feat/holochain-0.6-and-unified-plugin" }
holochain = { version = "0.6.1", default-features = false, features = ["sqlite-encrypted", "wasmer_sys", "transport-iroh"] }
holochain_types = { version = "0.6.1" }

log = "0.4"
tauri-plugin-log = "2.4.0"
tauri-plugin-opener = "2.2.7"
tauri-plugin-os = "2.2.1"
url2 = "0.0.6"
app_dirs2 = "2.5.5"
anyhow = "1"
fs2 = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.120"

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
