name: "test"
on:
  # Trigger the workflow on push or pull request to the maintained lines.
  push:
    branches: [ main, develop, main-0.7 ]
  pull_request:
    branches: [ main, develop, main-0.7 ]

jobs:
  testbuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install nix
        uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: |
            experimental-features = flakes nix-command

      - uses: cachix/cachix-action@v15
        with:
          name: holochain-ci

      - name: Install and test
        run: |
          nix develop --no-update-lock-file --accept-flake-config --command bash -c "npm i && npm t"
